# Generated by Django 6.0.3 on 2026-03-24 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('pan_card', 'PAN Card'), ('gst_certificate', 'GST Certificate'), ('bank_proof', 'Bank Proof'), ('incorporation_certificate', 'Incorporation Certificate'), ('msme_certificate', 'MSME Certificate'), ('address_proof', 'Address Proof')], max_length=50)),
                ('file_url', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendorrequest')),
            ],
            options={
                'db_table': 'vendor_documents',
            },
        ),
    ]
