# Generated by Django 6.0.3 on 2026-03-24 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_company_name', models.CharField(blank=True, max_length=255)),
                ('vendor_type', models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('domestic', 'Domestic'), ('foreign', 'Foreign'), ('government', 'Government'), ('employee', 'Employee')], max_length=20)),
                ('status', models.CharField(choices=[('link_sent', 'Link Sent'), ('form_submitted', 'Form Submitted'), ('l1_pending', 'L1 Pending'), ('l2_pending', 'L2 Pending'), ('l3_pending', 'L3 Pending'), ('sap_pending', 'SAP Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('clarification_requested', 'Clarification Requested')], default='link_sent', max_length=30)),
                ('registration_token', models.TextField(blank=True)),
                ('registration_token_expires', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('clarification_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('supply_category', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('tan_number', models.CharField(blank=True, max_length=20)),
                ('is_msme', models.BooleanField(default=False)),
                ('msme_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('branch_address', models.TextField(blank=True)),
                ('compliance_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='vendors.vendorrequest')),
            ],
            options={
                'db_table': 'vendor_registration_forms',
            },
        ),
        migrations.CreateModel(
            name='AdminAdditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(blank=True, max_length=50)),
                ('recall_account', models.CharField(blank=True, max_length=50)),
                ('vendor_group_type', models.CharField(blank=True, max_length=50)),
                ('tax_style', models.CharField(blank=True, max_length=50)),
                ('tax_code', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_additions', to='vendors.vendorrequest')),
            ],
            options={
                'db_table': 'admin_additions',
            },
        ),
    ]
