# Generated by Django 6.0.3 on 2026-03-24 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], max_length=5)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('clarification', 'Clarification')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('actioned_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_entries', to='vendors.vendorrequest')),
            ],
            options={
                'db_table': 'approval_workflow',
                'ordering': ['actioned_at'],
            },
        ),
    ]
