# Generated by Django 6.0.3 on 2026-03-24 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('ticket_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('form_submitted', 'Form Submitted'), ('l1_approved', 'L1 Approved'), ('l2_approved', 'L2 Approved'), ('l3_approved', 'L3 Approved'), ('clarification_requested', 'Clarification Requested'), ('rejected', 'Rejected'), ('vendor_code_created', 'Vendor Code Created')], max_length=40)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('vendor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorrequest')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
